CREATE TABLE `categories` (
	`cid` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`removed` ENUM('Y','N') NOT NULL DEFAULT 'N',
	PRIMARY KEY (`cid`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=20
;
