CREATE TABLE `users` (
	`uid` INT(11) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NULL DEFAULT NULL,
	`role` INT(11) NULL DEFAULT NULL,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lastlogin` DATETIME NOT NULL,
	`reset_token` VARCHAR(50) NULL DEFAULT NULL,
	`reset_token_expire` DATETIME NULL DEFAULT NULL,
	`removed` ENUM('Y','N') NOT NULL DEFAULT 'N',
	PRIMARY KEY (`uid`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=9
;
