CREATE TABLE `users` (
	`uid` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`passphrase` VARCHAR(255) NOT NULL,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lastlogin` DATETIME NOT NULL,
	PRIMARY KEY (`uid`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
