CREATE TABLE `versions` (
	`vid` INT(11) NOT NULL AUTO_INCREMENT,
	`tid` INT(11) NULL DEFAULT NULL,
	`user` INT(11) NOT NULL,
	`comment` TEXT NULL,
	`difference` TEXT NULL,
	`created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`vid`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=21
;
